### ISSUE TITLE
Blitzar requires 12060

### ISSUE THREAD

**Issue by CodeShakingSheep** [spaceandtimelabs/blitzar#184]
When I run the "Hello World" example from [sxt-proof-of-sql](https://github.com/spaceandtimelabs/sxt-proof-of-sql) with
```
cargo run --example hello_world --features="blitzar test"
```

I receive this output 
```
Warming up GPU...cbindings/backend.cc:55 panic: Update GPU drivers. The maximum supported version is 12040 but blitzar requires 12060
```

I'm running a GeForce MX150 on my Ubuntu and I'm already running the latest proprietary and tested driver (550).
![image](https://github.com/user-attachments/assets/600b4a47-f8f3-4ba4-9894-b11d05f4395a)

![image](https://github.com/user-attachments/assets/6d9589b7-b717-4b0b-aef0-2d77fc18da4b)

When I look for the latest Linux drivers on the NVIDIA website I see this
![image](https://github.com/user-attachments/assets/9fbaa5bc-dbaf-4d7c-a9d2-3d117e1d12bc)

So, I could possibly download and manually install the latest driver version 550.120. However, before I do that I would like to know if this driver would meet the `12060` requirement as I'm not sure to what this number refers to exactly. Thank you for shining some light on this issue.

**Comment by rnburn** [comment]
Those numbers are coming from the function cudaDriverGetVersion
https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART____VERSION.html#group__CUDART____VERSION_1g8a06ee14a0551606b7c780084d5564ab

The 12040 is referring to the latest version of the cuda toolkit your drivers support:
> Returns in *driverVersion the latest version of CUDA supported by the driver. The version is returned as (1000 major + 10 minor). For example, CUDA 9.2 would be represented by 9020. If no driver is installed, then 0 is returned as the driver version.

We're currently on cuda toolkit 12.6 update 1. If you look at the release notes, it will say what the minimum required driver is https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html

> CUDA 12.6 Update 1   >=560.35.03 (linux).    >=560.94 (windows)

Alternatively, you could also fix the version to this older release https://github.com/spaceandtimelabs/blitzar/releases/tag/v1.80.3
which was built with cuda toolkit 12.4 and (I think) should work with the drivers you already have installed.

**Comment by CodeShakingSheep** [comment]
Thanks @rnburn , I understand. Indeed, running `nvidia-smi` shows `CUDA Version: 12.4`. So, I think I can only do testing with blitzar 1.80.3.
